[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
casino_plinko = "Gk5Layof7VJwN281YnStuWCfVPWsivkJ8DRJp2brprfv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-rust = "cargo test-bpf --manifest-path programs/casino_plinko/Cargo.toml"
