[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
casino_plinko = "H3NfkuUXGiwNQK8f4xDkqVcPEWxUTRWJ3oLHyAeerGYd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
