[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
casino_plinko = "BEYxYPc7FMYqTVVS3129Fe8jv9NbEoekPx7qn1R1b7UF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
