[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
casino_plinko = "GLQ7L37VY5nq7Po39KxLxJYd63VNMCQU4rWuddNWM15z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
