[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
casino_plinko = "Fs8cFDXxUKJNGvCTqWaAzAMB5h7Qr8xLMLSnEiiVCDZn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
