[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
casino_plinko = "2JU147Qh1s54RJZPFdyZPvhNDJMpUfaHEHE4UPG27M7m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize_player = "anchor run initialize_player"
